version: "3.8"
services:
  frontend:
    build:
      context: ./mtaawetu-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
  backend:
    build:
      context: ./Backend # Adjust to the actual backend folder if it's different
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env # Path to the backend .env file
