# Generated by Django 5.1.2 on 2024-10-17 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KisiiReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=5, max_digits=7)),
                ('lon', models.DecimalField(decimal_places=5, max_digits=7)),
                ('givance_description', models.TextField(blank=True)),
                ('category_of_complaint', models.CharField(max_length=250)),
                ('category_of_grivance', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Pending', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KisiiReports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kisii Reports',
                'verbose_name_plural': 'Kisii Reports',
            },
        ),
    ]
