# Generated by Django 5.1.2 on 2024-10-18 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kisii', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kisiireports',
            old_name='givance_description',
            new_name='grivance_description',
        ),
    ]
