# Generated by Django 5.1.2 on 2024-10-30 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kisii', '0002_rename_givance_description_kisiireports_grivance_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('phonenumber', models.CharField(max_length=15)),
                ('residency', models.BooleanField(default=False)),
                ('ward', models.CharField(blank=True, max_length=30, null=True)),
                ('communicationMode', models.CharField(choices=[('Call', 'Call'), ('SMS', 'SMS'), ('WhatsApp', 'WhatsApp')], default='SMS', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
