# Generated by Django 5.1.2 on 2024-11-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kisii', '0004_alter_userprofile_residency'),
    ]

    operations = [
        migrations.AddField(
            model_name='kisiireports',
            name='suboptions',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
